import type { HomeContent } from "./types";

/**
 * Fixture aligned to Digital License Home demo (home-v7).
 * Swap getHomeContent() to CMS publish payload later.
 */
export const homeFixture: HomeContent = {
  navigation: [
    { label: "Nền tảng", href: "/about" },
    { label: "Sản phẩm", href: "/products" },
    { label: "Giải pháp", href: "/#solutions" },
    { label: "Tin tức", href: "/blog" },
    { label: "Hỗ trợ", href: "/faq" },
  ],
  hero: {
    visible: true,
    badge: "DIGITAL LICENSE PLATFORM",
    title: "Nền tảng phân phối bản quyền số",
    titleAccent: "toàn diện",
    subtitle:
      "Cung cấp công cụ mua và quản lý giấy phép phần mềm chính hãng — thanh toán rõ, giao đúng loại nhận, lưu trong Tài khoản.",
    ctaLabel: "Khám phá sản phẩm →",
    ctaHref: "/products",
    secondaryCtaLabel: "Dành cho doanh nghiệp",
    secondaryCtaHref: "/#solutions",
    trustItems: [
      {
        title: "100% Chính hãng",
        description: "Nguồn cung rõ ràng, hóa đơn đầy đủ.",
      },
      {
        title: "Giao hàng tức thì",
        description: "Key / tài khoản / kích hoạt sau thanh toán.",
      },
      {
        title: "Hỗ trợ 24/7",
        description: "Kênh hỗ trợ khi kích hoạt gặp sự cố.",
      },
    ],
  },
  partners: {
    title: "Đối tác tin cậy của KEYON",
    badges: ["ISO 27001 · GDPR", "PCI DSS Compliant"],
    items: [
      { id: "p1", name: "Microsoft", brandColor: "#00A4EF", visible: true },
      { id: "p2", name: "Adobe", brandColor: "#EB1000", visible: true },
      { id: "p3", name: "Autodesk", brandColor: "#0696D7", visible: true },
      { id: "p4", name: "VMware", brandColor: "#607078", visible: true },
      { id: "p5", name: "Kaspersky", brandColor: "#006D5C", visible: true },
      { id: "p6", name: "Acronis", brandColor: "#1A73E8", visible: true },
      { id: "p7", name: "Norton", brandColor: "#FFE01B", visible: true },
      { id: "p8", name: "McAfee", brandColor: "#C01818", visible: true },
    ],
  },
  categories: {
    visible: true,
    title: "Danh mục sản phẩm",
    viewAllHref: "/products",
    viewAllLabel: "Xem tất cả",
    items: [
      {
        id: "c1",
        title: "Windows",
        countLabel: "18 sản phẩm",
        href: "/products",
        icon: "windows",
      },
      {
        id: "c2",
        title: "Microsoft Office",
        countLabel: "12 sản phẩm",
        href: "/products",
        icon: "office",
      },
      {
        id: "c3",
        title: "Adobe",
        countLabel: "10 sản phẩm",
        href: "/products",
        icon: "adobe",
      },
      {
        id: "c4",
        title: "Cloud & Server",
        countLabel: "8 sản phẩm",
        href: "/products",
        icon: "cloud",
      },
      {
        id: "c5",
        title: "Bảo mật",
        countLabel: "14 sản phẩm",
        href: "/products",
        icon: "security",
      },
      {
        id: "c6",
        title: "Autodesk",
        countLabel: "9 sản phẩm",
        href: "/products",
        icon: "autodesk",
      },
      {
        id: "c7",
        title: "Backup",
        countLabel: "7 sản phẩm",
        href: "/products",
        icon: "backup",
      },
    ],
  },
  valueProps: {
    visible: false,
    items: [],
  },
  howItWorks: {
    visible: false,
    title: "Cách KEYON hoạt động",
    steps: [],
  },
  featured: {
    visible: true,
    title: "Sản phẩm nổi bật",
    viewAllHref: "/products",
    viewAllLabel: "Xem tất cả",
    items: [
      {
        id: "f1",
        brandName: "Windows",
        productName: "Windows 11 Pro",
        packageName: "License Retail",
        priceVnd: 2_550_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "windows",
        rating: 5,
        reviewCount: 128,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f2",
        brandName: "Windows",
        productName: "Windows 10 Pro",
        packageName: "License Retail",
        priceVnd: 1_850_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "windows",
        rating: 5,
        reviewCount: 98,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f3",
        brandName: "Office",
        productName: "Microsoft Office 2021",
        packageName: "Professional Plus",
        priceVnd: 2_750_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "office",
        rating: 5,
        reviewCount: 76,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f4",
        brandName: "Windows",
        productName: "Windows Server 2022",
        packageName: "Standard",
        priceVnd: 6_290_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "server",
        rating: 5,
        reviewCount: 34,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f5",
        brandName: "Kaspersky",
        productName: "Kaspersky Total Security",
        packageName: "1 Device / 1 Year",
        priceVnd: 450_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "security",
        rating: 5,
        reviewCount: 62,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
    ],
  },
  why: {
    visible: true,
    title: "Vì sao chọn KEYON?",
    subtitle:
      "Minh bạch đơn hàng, đúng loại nhận, lưu giấy phép trong Tài khoản — vận hành rõ ràng cho cá nhân và doanh nghiệp.",
    ctaLabel: "Tìm hiểu thêm →",
    ctaHref: "/about",
    items: [
      {
        id: "w1",
        title: "Bản quyền chính hãng",
        description: "Nguồn cung minh bạch, hóa đơn đầy đủ khi mua.",
        icon: "shield",
      },
      {
        id: "w2",
        title: "Giao hàng tức thì",
        description: "Nhận key, tài khoản hoặc kích hoạt ngay sau thanh toán.",
        icon: "bolt",
      },
      {
        id: "w3",
        title: "Giá tốt nhất",
        description: "So sánh gói và loại nhận rõ ràng trước khi mua.",
        icon: "price",
      },
      {
        id: "w4",
        title: "Thanh toán an toàn",
        description: "Chuẩn PCI DSS, nhiều cổng thanh toán được bảo vệ.",
        icon: "card",
      },
      {
        id: "w5",
        title: "Hỗ trợ 24/7",
        description: "Kênh hỗ trợ kích hoạt và xử lý sự cố mọi lúc.",
        icon: "support",
      },
      {
        id: "w6",
        title: "Hoàn tiền linh hoạt",
        description: "Chính sách hoàn tiền rõ ràng theo điều khoản.",
        icon: "refund",
      },
    ],
  },
  solutions: {
    visible: true,
    title: "Giải pháp cho doanh nghiệp",
    subtitle:
      "Quản lý giấy phép tập trung, tối ưu ngân sách và kết nối hệ thống — dành cho team IT & procurement.",
    ctaLabel: "Liên hệ tư vấn",
    ctaHref: "/contact",
    items: [
      {
        id: "sol1",
        title: "Quản lý tập trung",
        description: "Theo dõi giấy phép theo đơn vị, dự án và vòng đời sử dụng.",
        art: "bars",
      },
      {
        id: "sol2",
        title: "Tối ưu chi phí",
        description: "Báo cáo ngân sách phần mềm, tránh mua trùng và lãng phí license.",
        art: "trend",
      },
      {
        id: "sol3",
        title: "Tích hợp API linh hoạt",
        description: "Kết nối hệ thống nội bộ, tự động hóa cấp phát (roadmap).",
        art: "api",
      },
      {
        id: "sol4",
        title: "Hỗ trợ chuyên nghiệp",
        description: "Kênh CS ưu tiên, SLA rõ ràng cho tài khoản doanh nghiệp.",
        art: "headset",
      },
    ],
  },
  news: {
    visible: true,
    title: "Tin tức & cập nhật",
    viewAllHref: "/blog",
    viewAllLabel: "Xem tất cả bài viết",
    items: [
      {
        id: "n1",
        title: "5 lý do nên mua phần mềm bản quyền",
        excerpt: "An toàn, ổn định và hỗ trợ dài hạn cho doanh nghiệp.",
        dateLabel: "20/05/2024",
        href: "/blog",
        tag: "Windows",
        tagTone: "win",
      },
      {
        id: "n2",
        title: "Windows 11: tính năng mới nổi bật",
        excerpt: "Những điểm đáng chú ý khi nâng cấp máy làm việc.",
        dateLabel: "15/05/2024",
        href: "/blog",
        tag: "Microsoft",
        tagTone: "ms",
      },
      {
        id: "n3",
        title: "Bảo vệ thiết bị với Microsoft Defender",
        excerpt: "Cách bảo vệ máy tính và dữ liệu doanh nghiệp.",
        dateLabel: "10/05/2024",
        href: "/blog",
        tag: "Bảo mật",
        tagTone: "sec",
      },
      {
        id: "n4",
        title: "Chọn gói Creative Cloud phù hợp",
        excerpt: "So sánh gói Adobe theo nhu cầu cá nhân và team.",
        dateLabel: "05/05/2024",
        href: "/blog",
        tag: "Adobe",
        tagTone: "adobe",
      },
    ],
  },
  ctaBanner: {
    visible: true,
    title: "Sẵn sàng trải nghiệm giải pháp số tối ưu?",
    subtitle: "Hàng nghìn khách hàng đã tin dùng KEYON để mua và quản lý giấy phép.",
    ctaLabel: "Tạo tài khoản ngay →",
    ctaHref: "/register",
  },
  footer: {
    blurb:
      "Nền tảng phân phối bản quyền số — thanh toán rõ, nhận hàng rõ, quản lý trong Tài khoản.",
    columns: [
      {
        title: "Sản phẩm",
        links: [
          { label: "Windows", href: "/products" },
          { label: "Microsoft Office", href: "/products" },
          { label: "Adobe", href: "/products" },
          { label: "Bảo mật", href: "/products" },
          { label: "Autodesk", href: "/products" },
        ],
      },
      {
        title: "Về KEYON",
        links: [
          { label: "Giới thiệu", href: "/about" },
          { label: "Tin tức", href: "/blog" },
          { label: "Chính sách", href: "/policy" },
          { label: "Điều khoản", href: "/terms" },
          { label: "Liên hệ", href: "/contact" },
        ],
      },
      {
        title: "Hỗ trợ",
        links: [
          { label: "Trung tâm hỗ trợ", href: "/faq" },
          { label: "Hướng dẫn nhận hàng", href: "/about" },
          { label: "FAQ", href: "/faq" },
          { label: "Yêu cầu hỗ trợ", href: "/contact" },
        ],
      },
      {
        title: "Liên hệ",
        links: [
          { label: "+84 900 000 000", href: "tel:+84900000000" },
          { label: "support@keyon.vn", href: "mailto:support@keyon.vn" },
          { label: "Đà Nẵng, Việt Nam", href: "/contact" },
        ],
      },
    ],
    copyright: "© 2024 KEYON. All rights reserved.",
    legalLinks: [
      { label: "Điều khoản sử dụng", href: "/terms" },
      { label: "Chính sách bảo mật", href: "/policy" },
    ],
    contactLines: ["+84 900 000 000", "support@keyon.vn", "Đà Nẵng, Việt Nam"],
  },
};
