import type { HomeContent } from "./types";

/**
 * Fixture aligned to Digital License Home demo (home-v7).
 * Swap getHomeContent() to CMS publish payload later.
 */
export const homeFixture: HomeContent = {
  navigation: [
    { label: "Sản phẩm", href: "/products" },
    { label: "Giải pháp", href: "/#solutions" },
    { label: "Doanh nghiệp", href: "/contact" },
    { label: "Tài nguyên", href: "/blog" },
    { label: "Hỗ trợ", href: "/faq" },
  ],
  brand: {
    brandName: "KEYON",
    tagline: "Digital License Platform",
  },
  hero: {
    visible: true,
    badge: "DIGITAL LICENSE PLATFORM",
    title: "Nền tảng phân phối bản quyền số",
    titleAccent: "toàn diện",
    subtitle:
      "Mua, triển khai và quản lý bản quyền phần mềm, cloud và dịch vụ số trên một nền tảng duy nhất. Dành cho cá nhân, đội nhóm và doanh nghiệp.",
    ctaLabel: "Khám phá sản phẩm →",
    ctaHref: "/products",
    secondaryCtaLabel: "Dành cho doanh nghiệp",
    secondaryCtaHref: "/#solutions",
    trustItems: [
      {
        title: "100% Chính hãng",
        description: "Nguồn cung rõ ràng, hóa đơn đầy đủ.",
      },
      {
        title: "Giao hàng tức thì",
        description: "Key / tài khoản / kích hoạt sau thanh toán.",
      },
      {
        title: "Hỗ trợ kích hoạt",
        description: "Ticket trong Tài khoản khi gặp sự cố.",
      },
    ],
  },
  partners: {
    title: "Thương hiệu phần mềm trên KEYON",
    badges: ["Bản quyền chính hãng", "Thanh toán rõ ràng"],
    items: [
      { id: "p1", name: "Microsoft", brandColor: "#00A4EF", visible: true },
      { id: "p2", name: "Adobe", brandColor: "#EB1000", visible: true },
      { id: "p3", name: "Autodesk", brandColor: "#0696D7", visible: true },
      { id: "p4", name: "VMware", brandColor: "#607078", visible: true },
      { id: "p5", name: "Kaspersky", brandColor: "#006D5C", visible: true },
      { id: "p6", name: "Acronis", brandColor: "#1A73E8", visible: true },
      { id: "p7", name: "Norton", brandColor: "#FFE01B", visible: true },
      { id: "p8", name: "McAfee", brandColor: "#C01818", visible: true },
    ],
  },
  categories: {
    visible: true,
    title: "Danh mục sản phẩm",
    viewAllHref: "/products",
    viewAllLabel: "Xem tất cả",
    items: [
      {
        id: "c1",
        title: "Windows",
        countLabel: "18 sản phẩm",
        href: "/products",
        icon: "windows",
      },
      {
        id: "c2",
        title: "Microsoft Office",
        countLabel: "12 sản phẩm",
        href: "/products",
        icon: "office",
      },
      {
        id: "c3",
        title: "Adobe",
        countLabel: "10 sản phẩm",
        href: "/products",
        icon: "adobe",
      },
      {
        id: "c4",
        title: "Cloud & Server",
        countLabel: "8 sản phẩm",
        href: "/products",
        icon: "cloud",
      },
      {
        id: "c5",
        title: "Bảo mật",
        countLabel: "14 sản phẩm",
        href: "/products",
        icon: "security",
      },
      {
        id: "c6",
        title: "Autodesk",
        countLabel: "9 sản phẩm",
        href: "/products",
        icon: "autodesk",
      },
      {
        id: "c7",
        title: "Backup",
        countLabel: "7 sản phẩm",
        href: "/products",
        icon: "backup",
      },
    ],
  },
  valueProps: {
    visible: false,
    items: [],
  },
  howItWorks: {
    visible: true,
    title: "Cách KEYON hoạt động",
    steps: [
      {
        id: "h1",
        title: "Chọn gói",
        description: "Xem loại nhận (key / tài khoản) và giá trước khi đặt.",
      },
      {
        id: "h2",
        title: "Thanh toán",
        description: "Chuyển khoản / VietQR theo hướng dẫn trên trang thanh toán.",
      },
      {
        id: "h3",
        title: "Nhận trong Tài khoản",
        description:
          "Sau khi hệ thống xác nhận thanh toán, mở Đơn hàng / Tài sản để lấy deliverable.",
      },
    ],
  },
  featured: {
    visible: true,
    title: "Sản phẩm nổi bật",
    viewAllHref: "/products",
    viewAllLabel: "Xem tất cả",
    items: [
      {
        id: "f1",
        brandName: "Windows",
        productName: "Windows 11 Pro",
        packageName: "License Retail",
        priceVnd: 2_550_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "windows",
        rating: undefined,
        reviewCount: undefined,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f2",
        brandName: "Windows",
        productName: "Windows 10 Pro",
        packageName: "License Retail",
        priceVnd: 1_850_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "windows",
        rating: undefined,
        reviewCount: undefined,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f3",
        brandName: "Office",
        productName: "Microsoft Office 2021",
        packageName: "Professional Plus",
        priceVnd: 2_750_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "office",
        rating: undefined,
        reviewCount: undefined,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f4",
        brandName: "Windows",
        productName: "Windows Server 2022",
        packageName: "Standard",
        priceVnd: 6_290_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "server",
        rating: undefined,
        reviewCount: undefined,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
      {
        id: "f5",
        brandName: "Kaspersky",
        productName: "Kaspersky Total Security",
        packageName: "1 Device / 1 Year",
        priceVnd: 450_000,
        receiveLabel: "Key",
        receiveKind: "key",
        mark: "security",
        rating: undefined,
        reviewCount: undefined,
        ctaLabel: "Thanh toán ngay",
        href: "/products",
      },
    ],
  },
  why: {
    visible: true,
    title: "Vì sao chọn KEYON?",
    subtitle:
      "Minh bạch trước khi mua, lưu license trong Tài khoản, hỗ trợ tiếng Việt.",
    ctaLabel: "Tìm hiểu thêm →",
    ctaHref: "/about",
    items: [
      {
        id: "w1",
        title: "Nguồn cung minh bạch",
        description:
          "Thông tin loại license và hình thức nhận được hiển thị rõ trước khi mua.",
        icon: "shield",
      },
      {
        id: "w2",
        title: "Quản lý tập trung",
        description: "Đơn hàng và license được lưu trong Tài khoản KEYON.",
        icon: "card",
      },
      {
        id: "w3",
        title: "Hóa đơn doanh nghiệp",
        description: "Hỗ trợ chứng từ/hóa đơn theo điều kiện áp dụng.",
        icon: "price",
      },
      {
        id: "w4",
        title: "Hỗ trợ tiếng Việt",
        description: "Hỗ trợ trước và sau khi mua qua ticket trong Tài khoản.",
        icon: "support",
      },
      {
        id: "w5",
        title: "Thanh toán rõ ràng",
        description:
          "VietQR / chuyển khoản theo hướng dẫn trên trang thanh toán — theo dõi trạng thái trong đơn hàng.",
        icon: "bolt",
      },
      {
        id: "w6",
        title: "Chính sách hoàn tiền rõ",
        description:
          "Điều kiện hoàn tiền được ghi trong chính sách / điều khoản — không ẩn sau khi mua.",
        icon: "refund",
      },
    ],
  },
  solutions: {
    visible: true,
    kicker: "Giải pháp cho doanh nghiệp",
    title: "Phần mềm và cloud, được quản lý tại một nơi",
    subtitle:
      "Từ một vài giấy phép đến hàng trăm người dùng, KEYON giúp doanh nghiệp mua, triển khai và quản lý phần mềm dễ dàng hơn.",
    ctaLabel: "Khám phá giải pháp →",
    ctaHref: "/products",
    secondaryCtaLabel: "Liên hệ tư vấn",
    secondaryCtaHref: "/contact",
    items: [
      {
        id: "sol1",
        title: "Software Licensing",
        description:
          "Mua và quản lý license tập trung, theo dõi thiết bị và thời hạn.",
        art: "bars",
      },
      {
        id: "sol2",
        title: "Cloud & Subscription",
        description: "Quản lý cloud services và subscription theo tổ chức.",
        art: "trend",
      },
      {
        id: "sol3",
        title: "Security & Backup",
        description: "Bảo mật endpoint, dữ liệu và continuity.",
        art: "shield",
      },
      {
        id: "sol4",
        title: "License Management",
        description: "Theo dõi license, renewal, người dùng và chi phí.",
        art: "stack",
      },
    ],
  },
  news: {
    visible: true,
    title: "Tin tức & cập nhật",
    viewAllHref: "/blog",
    viewAllLabel: "Xem tất cả bài viết",
    items: [
      {
        id: "n1",
        title: "5 lý do nên mua phần mềm bản quyền",
        excerpt: "An toàn, ổn định và hỗ trợ dài hạn cho doanh nghiệp.",
        dateLabel: "20/05/2024",
        href: "/blog",
        tag: "Windows",
        tagTone: "win",
      },
      {
        id: "n2",
        title: "Windows 11: tính năng mới nổi bật",
        excerpt: "Những điểm đáng chú ý khi nâng cấp máy làm việc.",
        dateLabel: "15/05/2024",
        href: "/blog",
        tag: "Microsoft",
        tagTone: "ms",
      },
      {
        id: "n3",
        title: "Bảo vệ thiết bị với Microsoft Defender",
        excerpt: "Cách bảo vệ máy tính và dữ liệu doanh nghiệp.",
        dateLabel: "10/05/2024",
        href: "/blog",
        tag: "Bảo mật",
        tagTone: "sec",
      },
      {
        id: "n4",
        title: "Chọn gói Creative Cloud phù hợp",
        excerpt: "So sánh gói Adobe theo nhu cầu cá nhân và team.",
        dateLabel: "05/05/2024",
        href: "/blog",
        tag: "Adobe",
        tagTone: "adobe",
      },
    ],
  },
  ctaBanner: {
    visible: true,
    title: "Cần giải pháp license cho doanh nghiệp?",
    subtitle:
      "KEYON hỗ trợ mua, triển khai và quản lý phần mềm / cloud theo nhu cầu tổ chức — vẫn giữ trải nghiệm mua lẻ rõ ràng cho cá nhân.",
    ctaLabel: "Liên hệ tư vấn →",
    ctaHref: "/contact",
  },
  footer: {
    brandName: "KEYON",
    blurb:
      "Nền tảng phân phối và quản lý bản quyền phần mềm, cloud và dịch vụ số.",
    supportEmail: "support@keyon.vn",
    paymentBadges: ["VietQR", "Chuyển khoản"],
    columns: [
      {
        title: "Sản phẩm",
        links: [
          { label: "Windows", href: "/products" },
          { label: "Microsoft Office", href: "/products" },
          { label: "Adobe", href: "/products" },
          { label: "Bảo mật", href: "/products" },
          { label: "Cloud & Server", href: "/products" },
          { label: "Tất cả sản phẩm", href: "/products" },
        ],
      },
      {
        title: "Giải pháp",
        links: [
          { label: "Software Licensing", href: "/#solutions" },
          { label: "Cloud", href: "/#solutions" },
          { label: "Security & Backup", href: "/#solutions" },
          { label: "License Management", href: "/#solutions" },
          { label: "API", href: "/contact" },
        ],
      },
      {
        title: "Công ty & Hỗ trợ",
        links: [
          { label: "Giới thiệu", href: "/about" },
          { label: "Tin tức", href: "/blog" },
          { label: "Trung tâm hỗ trợ", href: "/faq" },
          { label: "FAQ", href: "/faq" },
          { label: "Liên hệ", href: "/contact" },
        ],
      },
      {
        title: "Thông tin doanh nghiệp",
        links: [
          { label: "KEYON", href: "/about" },
          { label: "support@keyon.vn", href: "mailto:support@keyon.vn" },
          { label: "Đà Nẵng, Việt Nam", href: "/contact" },
          { label: "Liên hệ tư vấn", href: "/contact" },
        ],
      },
    ],
    copyright: "© 2026 KEYON. All rights reserved.",
    legalLinks: [
      { label: "Điều khoản", href: "/terms" },
      { label: "Chính sách bảo mật", href: "/policy" },
      { label: "Chính sách thanh toán", href: "/policy" },
      { label: "Chính sách giao hàng điện tử", href: "/policy" },
      { label: "Quy định sản phẩm số", href: "/policy" },
    ],
    contactLines: ["support@keyon.vn", "Đà Nẵng, Việt Nam"],
  },
};
