/**
 * Account portal UI chrome — hardcode (không CMS).
 * Ops-editable fields live in CmsAccount (server/cms/types).
 */
export const ACCOUNT_UI = {
  orderBackLabel: "Quay lại đơn hàng",
  orderPageTitle: "Chi tiết đơn hàng",
  orderInvoiceCta: "Tải hóa đơn",
  orderStatusCompleted: "Đã hoàn thành",
  orderStatusProcessing: "Đang xử lý",
  orderStatusPendingPay: "Chờ thanh toán",
  orderCodeLabel: "Đơn hàng",
  orderTimeLabel: "Thời gian đặt hàng",
  orderPaymentMethodLabel: "Phương thức thanh toán",
  productsTitle: "Sản phẩm trong đơn",
  licenseKeyLabel: "License Key của bạn",
  timelineTitle: "Lịch sử đơn hàng",
  summaryTitle: "Tóm tắt đơn hàng",
  feeLabel: "Phí giao dịch",
  vatIncludedNote: "Đã bao gồm VAT",
  paymentInfoTitle: "Thông tin thanh toán",
  transactionIdLabel: "Mã giao dịch",
  paymentTimeLabel: "Thời gian thanh toán",
  paymentStatusLabel: "Trạng thái",
  profilePageTitle: "Thông tin tài khoản",
  profilePageLead: "Quản lý thông tin cá nhân và bảo mật tài khoản của bạn",
  overviewStatsTitle: "Tổng quan tài khoản",
  overviewPeriod7d: "7 ngày qua",
  overviewPeriod30d: "30 ngày qua",
  overviewPeriod90d: "90 ngày qua",
  overviewStatOrders: "Đơn hàng",
  overviewStatLicenses: "License",
  overviewStatActivating: "Đang kích hoạt",
  overviewStatCompleted: "Đã hoàn tất",
  overviewRecentOrdersTitle: "Đơn hàng gần đây",
  overviewViewAll: "Xem tất cả",
  overviewSpendTitle: "Chi tiêu",
  overviewSpendTotalLabel: "Tổng chi tiêu",
  overviewSpendComparePrefix: "so với",
  overviewLicensesTitle: "License của tôi",
  overviewLicenseActivating: "Đang kích hoạt",
  overviewLicenseReady: "Sẵn sàng kích hoạt",
  overviewLicenseExpired: "Hết hạn",
  overviewLicenseUnavailable: "Không khả dụng",
  overviewShortcutsTitle: "Lối tắt nhanh",
  overviewShortcutShop: "Mua sản phẩm",
  overviewShortcutLicenses: "License của tôi",
  overviewShortcutOrders: "Đơn hàng của tôi",
  overviewShortcutSupport: "Yêu cầu hỗ trợ",
  overviewShortcutFaq: "Câu hỏi thường gặp",
  overviewShortcutGuide: "Hướng dẫn sử dụng",
  overviewNotiTitle: "Thông báo",
  overviewEmptyOrders: "Bạn chưa có đơn hàng gần đây.",
  overviewEmptyNoti: "Chưa có thông báo mới.",
  profileEditCta: "Chỉnh sửa",
  profileVerifiedBadge: "Đã xác thực",
  profileMemberSincePrefix: "Thành viên từ",
  profileOrdersStatLabel: "Đơn hàng",
  profileOrdersStatSub: "Đã hoàn thành",
  profileSpendStatLabel: "Tổng chi tiêu",
  profileSpendStatSub: "Tổng giá trị",
  profileAccountStatLabel: "Tài khoản",
  profileAccountStatSub: "Bảo mật tốt",
  profilePersonalTitle: "Thông tin cá nhân",
  profileSecurityCardTitle: "Bảo mật tài khoản",
  profileSecurityManageCta: "Quản lý bảo mật",
  profileActivityTitle: "Hoạt động gần đây",
  profileActivityViewAll: "Xem tất cả hoạt động",
  profileNotiTitle: "Thông báo",
  profileNotiViewAll: "Xem tất cả",
  profilePasswordLabel: "Mật khẩu",
  profile2faLabel: "Xác thực hai bước (2FA)",
  profile2faOn: "Đã bật",
  profile2faOff: "Chưa bật",
  profileEmailVerifiedLabel: "Email xác thực",
  profileFieldName: "Họ và tên",
  profileFieldEmail: "Email",
  profileFieldPhone: "Số điện thoại",
  profileFieldDob: "Ngày sinh",
  profileFieldAddress: "Địa chỉ",
  profileEmptyValue: "Chưa cập nhật",
  licensesPageTitle: "License của tôi",
  licensesPageLead: "Quản lý tất cả license bạn đã mua tại KEYON.",
  licensesTabAll: "Tất cả",
  licensesTabActive: "Đang sử dụng",
  licensesTabExpired: "Hết hạn",
  licensesTabPending: "Chưa kích hoạt",
  licensesSearchPlaceholder: "Tìm kiếm license, sản phẩm…",
  licensesFilterCta: "Bộ lọc",
  licensesEmptyTitle: "Chưa có license",
  licensesEmptyBody:
    "License sẽ xuất hiện tại đây sau khi đơn được giao thành công.",
  licensesKeyLabel: "License Key",
  licensesQtyLabel: "Số lượng",
  licensesPurchasedLabel: "Ngày mua",
  licensesExpiryLabel: "Hạn sử dụng",
  licensesLifetimeValue: "Vĩnh viễn",
  licensesPendingNote:
    "License chưa được kích hoạt. Vui lòng kích hoạt để sử dụng.",
  licensesActivatedLabel: "Nhận license",
  licensesStatusActive: "Đang sử dụng",
  licensesStatusPending: "Chưa kích hoạt",
  licensesStatusExpired: "Hết hạn",
  securityTitle: "Bảo mật tài khoản",
  notificationsTitle: "Thông báo",
  notificationsEmpty: "Chưa có thông báo mới.",
  ticketsTitle: "Yêu cầu hỗ trợ",
  ticketsEmpty: "Bạn chưa có yêu cầu hỗ trợ nào.",
  ticketFormSubjectLabel: "Tiêu đề",
  ticketFormBodyLabel: "Nội dung",
  ticketFormSubmit: "Gửi yêu cầu",
  ordersPageTitle: "Đơn hàng của tôi",
  ordersPageLead: "Quản lý và theo dõi tất cả đơn hàng của bạn tại KEYON",
  ordersSpendLabel: "Tổng chi tiêu",
  ordersSpendPeriodLabel: "12 tháng qua",
  ordersTabAll: "Tất cả đơn",
  ordersTabSuccess: "Thành công",
  ordersTabProcessing: "Đang xử lý",
  ordersTabCancelled: "Đã hủy",
  ordersSearchPlaceholder: "Tìm kiếm đơn hàng…",
  ordersFilterCta: "Bộ lọc",
  ordersEmptyTitle: "Chưa có đơn hàng",
  ordersEmptyBody: "Bạn chưa đặt đơn nào trên KEYON.",
  ordersColOrder: "Đơn hàng",
  ordersColProduct: "Sản phẩm",
  ordersColDate: "Ngày đặt",
  ordersColPayment: "Thanh toán",
  ordersColStatus: "Trạng thái",
  ordersColTotal: "Tổng tiền",
  ordersDetailCta: "Xem chi tiết",
  ordersTxnPrefix: "Mã GD",
  ordersQtySuffix: "License",
  ordersStatusSuccess: "Thành công",
  ordersStatusSuccessSub: "Đã hoàn tất",
  ordersStatusProcessing: "Đang xử lý",
  ordersStatusProcessingSub: "Đang xác nhận",
  ordersStatusCancelled: "Đã hủy",
  ordersStatusCancelledSub: "Đơn hàng đã hủy",
  ordersStatusPendingPay: "Chờ thanh toán",
  ordersStatusPendingPaySub: "Chưa nhận tiền",
} as const;

export type AccountUiChrome = typeof ACCOUNT_UI;
